import fs from 'node:fs';import path from 'node:path';
const U=process.env.SITE_URL||'https://alkiroungroup.com';
const R=f=>JSON.parse(fs.readFileSync('content/'+f+'.json','utf8'));
const S=R('site'),C={products:R('products').items||[],works:R('works').items||[],local:R('local').items||[],foreign:R('foreign').items||[]};
const E=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const T=(o,k,l)=>o[k+'_'+l]||o[k+'_ar']||'';
const seen=new Set(),PS=C.products.map((p,i)=>{let s=(p.name_en||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'p'+(i+1);if(seen.has(s))s+='-'+(i+1);seen.add(s);return s});
const L={ar:{dir:'rtl',home:'الرئيسية',products:'منتجاتنا',works:'أعمالنا',partners:'الشراكات',contact:'تواصل معنا',local:'موردينا من الداخل',foreign:'موردينا من الخارج',about:'من نحن',why:'لماذا نحن',quote:'اطلب عرض سعر',browse:'استعرض المنتجات',feat:'منتجات مختارة',all:'كل المنتجات',empty:'قريباً',phone:'التليفون',email:'الإيميل',addr:'العنوان',wa:'واتساب',rights:'جميع الحقوق محفوظة',sw:'English',cta:'تحتاج منتجاً أو شريكاً موثوقاً؟',msg:'أرغب في عرض سعر لمنتج: '},
en:{dir:'ltr',home:'Home',products:'Products',works:'Our Work',partners:'Partnerships',contact:'Contact',local:'Local Suppliers',foreign:'International Suppliers',about:'About Us',why:'Why Us',quote:'Request a quote',browse:'Browse products',feat:'Featured products',all:'All products',empty:'Coming soon',phone:'Phone',email:'Email',addr:'Address',wa:'WhatsApp',rights:'All rights reserved',sw:'العربية',cta:'Need a product or a reliable partner?',msg:'I would like a quote for: '}};
const NAV=[['','home'],['products/','products'],['works/','works'],['partners/','partners'],['contact/','contact']];
const pages=[];const W=(f,h)=>{f=path.join('dist',f);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,h)};
const card=(p,l,link)=>{const im=p.image?`<img src="${E(p.image)}" alt="${E(T(p,'name',l))}" loading="lazy">`:`<img class="ph" src="/assets/logo.png" alt="">`;const tag=T(p,'category',l)||T(p,'country',l);const b=`<div class="im">${im}</div><div class="tx">${tag?`<span class="tag">${E(tag)}</span>`:''}<h3>${E(T(p,'name',l))}</h3><p>${E(T(p,'desc',l))}</p></div>`;return link?`<a class="card" href="${link}">${b}</a>`:`<article class="card">${b}</article>`};
const grid=(a,l,f)=>a.length?`<div class="grid">${a.map(f).join('')}</div>`:`<p class="muted">${L[l].empty}</p>`;
const wa=t=>`https://wa.me/${S.whatsapp}?text=${encodeURIComponent(t)}`;
const SV={fb:'<svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="24" fill="#1877F2"/><path fill="#fff" d="M26.5 38V26h4l.7-4.8h-4.7v-3c0-1.4.5-2.4 2.5-2.4h2.4V11.6c-.4-.1-1.9-.2-3.5-.2-3.6 0-6 2.2-6 6.2v3.6h-4V26h4v12h4.6z"/></svg>',li:'<svg viewBox="0 0 48 48"><rect width="48" height="48" rx="10" fill="#0A66C2"/><path fill="#fff" d="M13 19h5v16h-5zM15.5 11a2.9 2.9 0 1 1 0 5.800 2.900 2.900 0 0 1 0-5.800zM21 19h4.800v2.200c.7-1.300 2.400-2.600 5-2.600 5.100 0 6 3.300 6 7.700V35h-5v-7.600c0-1.800 0-4.100-2.500-4.100s-2.900 1.900-2.900 4V35H21z"/></svg>',wa:'<svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="24" fill="#25D366"/><path fill="#fff" d="M24 11a13 13 0 0 0-11.200 19.600L11 37l6.600-1.700A13 13 0 1 0 24 11zm0 2.400a10.600 10.600 0 1 1-5.400 19.700l-.4-.2-3.900 1 1-3.800-.3-.4A10.600 10.600 0 0 1 24 13.400zm-4.600 5.300c-.3 0-.7.100-1 .5-.4.400-1.300 1.300-1.300 3.100s1.400 3.600 1.600 3.800c.2.300 2.700 4.300 6.600 5.800 3.300 1.300 3.900 1 4.600.9.700-.1 2.300-.9 2.600-1.800.3-.9.3-1.600.2-1.800-.1-.2-.4-.3-.8-.5l-2.700-1.300c-.4-.2-.6-.2-.9.200-.3.400-1 1.300-1.300 1.600-.2.300-.5.300-.9.100-.4-.2-1.700-.6-3.200-2-1.200-1.100-2-2.400-2.200-2.800-.2-.4 0-.6.200-.8l.6-.7c.2-.2.3-.4.400-.7.100-.3.100-.5 0-.7l-1.200-3c-.3-.7-.6-.7-.9-.7z"/></svg>'};
const IMG={fb:'facebook',wa:'whatsapp'};
const ic=(k,u,n)=>`<a class="ic" href="${E(u)}" target="_blank" rel="noopener" aria-label="${n}" title="${n}">${IMG[k]?`<img src="/assets/icons/${IMG[k]}.png" alt="" width="48" height="48">`:SV[k]}</a>`;
const soc=()=>[['fb',S.facebook,'Facebook'],['li',S.linkedin,'LinkedIn']].filter(x=>x[1]).map(x=>ic(...x)).join('');
const contact=l=>`<section class="contact"><h2>${L[l].contact}</h2><p>${L[l].phone}: <a href="tel:${E(S.phone)}" dir="ltr">${E(S.phone)}</a></p><p>${L[l].email}: <a href="mailto:${E(S.email)}">${E(S.email)}</a></p><p>${L[l].addr}: ${E(T(S,'address',l))}</p><div class="icons">${ic('wa',wa(''),L[l].wa)}${soc()}</div></section>`;
function page(l,rel,title,desc,body,ld=[]){pages.push(rel);const o=l=='ar'?'en':'ar',d=L[l],url=`${U}/${l}/${rel}`;
const org={'@context':'https://schema.org','@type':'Organization',name:T(S,'name',l),url:U,logo:U+'/assets/logo.png',telephone:S.phone,email:S.email,sameAs:[S.facebook,S.linkedin].filter(Boolean)};
W(`${l}/${rel}index.html`,`<!doctype html><html lang="${l}" dir="${d.dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(title)}</title><meta name="description" content="${E(desc)}"><link rel="canonical" href="${url}">
<link rel="alternate" hreflang="ar" href="${U}/ar/${rel}"><link rel="alternate" hreflang="en" href="${U}/en/${rel}"><link rel="alternate" hreflang="x-default" href="${U}/ar/${rel}">
<meta property="og:title" content="${E(title)}"><meta property="og:description" content="${E(desc)}"><meta property="og:image" content="${U}/assets/logo.png"><meta property="og:url" content="${url}"><link rel="icon" href="/assets/logo.png">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css">
${[org,...ld].map(x=>`<script type="application/ld+json">${JSON.stringify(x)}</script>`).join('')}</head><body>
<header><div class="bar"><a class="brand" href="/${l}/"><img src="/assets/logo.png" alt="" width="46" height="46"><span><b>${E(T(S,'name',l))}</b><small>${E(T(S,'sub',l))}</small></span></a><nav>${NAV.map(([r,k])=>`<a href="/${l}/${r}"${rel.split('/')[0]==r.split('/')[0]?' class="on"':''}>${d[k]}</a>`).join('')}</nav><a class="sw" href="/${o}/${rel}" hreflang="${o}">${d.sw}</a></div></header>
<main>${body}</main><footer><div>© ${new Date().getFullYear()} ${E(T(S,'name',l))} — ${d.rights}</div><div class="fs">${ic('wa',wa(''),L[l].wa)}${soc()}</div></footer></body></html>`)}
for(const l of ['ar','en']){const d=L[l],nm=T(S,'name',l),sub=T(S,'sub',l);
page(l,'',`${nm} | ${sub}`,`${T(S,'tagline',l)} — ${T(S,'about',l).slice(0,120)}`,
`<section class="hero"><div><h1>${E(nm)}</h1><p class="sub">${E(sub)}</p><p class="lead">${E(T(S,'tagline',l))}</p><p><a class="btn" href="/${l}/products/">${d.browse}</a> <a class="btn alt" href="${wa('')}">${d.quote}</a></p></div><div class="logo"><img src="/assets/logo.png" alt="${E(nm)}" width="300" height="300"></div></section>
<section class="blk"><h2>${d.about}</h2><p class="lead">${E(T(S,'about',l))}</p></section>
<section class="blk"><h2>${d.why}</h2><div class="why">${(S.why||[]).map(w=>`<div><h3>${E(T(w,'title',l))}</h3><p>${E(T(w,'text',l))}</p></div>`).join('')}</div></section>
<section class="blk"><h2>${d.feat}</h2>${grid(C.products.slice(0,6),l,(p,i)=>card(p,l,`/${l}/products/${PS[C.products.indexOf(p)]}/`))}<p><a class="btn alt" href="/${l}/products/">${d.all}</a></p></section>
<section class="cta"><h2>${d.cta}</h2><p><a class="btn" href="/${l}/contact/">${d.contact}</a></p></section>`);
page(l,'products/',`${d.products} | ${nm}`,`${d.products} — ${nm}`,`<h1>${d.products}</h1>${grid(C.products,l,p=>card(p,l,`/${l}/products/${PS[C.products.indexOf(p)]}/`))}`);
C.products.forEach((p,i)=>{const pn=T(p,'name',l),ds=T(p,'desc',l)||`${pn} — ${nm}`;
page(l,`products/${PS[i]}/`,`${pn} | ${nm}`,ds.slice(0,160),`<nav class="crumb"><a href="/${l}/">${d.home}</a> › <a href="/${l}/products/">${d.products}</a> › ${E(pn)}</nav><article class="prod"><div class="im">${p.image?`<img src="${E(p.image)}" alt="${E(pn)}">`:`<img class="ph" src="/assets/logo.png" alt="">`}</div><div><span class="tag">${E(T(p,'category',l))}</span><h1>${E(pn)}</h1><p class="lead">${E(ds)}</p><p><a class="btn" href="${wa(d.msg+pn)}">${d.quote}</a></p></div></article>`,
[{'@context':'https://schema.org','@type':'Product',name:pn,description:ds,category:T(p,'category',l),image:p.image?U+p.image:U+'/assets/logo.png'}])});
page(l,'works/',`${d.works} | ${nm}`,`${d.works} — ${nm}`,`<h1>${d.works}</h1>${grid(C.works,l,p=>card(p,l))}`);
page(l,'partners/',`${d.partners} | ${nm}`,`${d.partners} — ${nm}`,`<h1>${d.partners}</h1><h2>${d.foreign}</h2>${grid(C.foreign,l,p=>card(p,l))}<h2>${d.local}</h2>${grid(C.local,l,p=>card(p,l))}`);
page(l,'contact/',`${d.contact} | ${nm}`,`${d.contact} — ${nm}`,contact(l))}
W('index.html','<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Al Kiroun Group</title><link rel="canonical" href="'+U+'/ar/"><meta http-equiv="refresh" content="0;url=/ar/"><script>if((navigator.language||"").indexOf("en")==0)location.replace("/en/")</script></head><body><a href="/ar/">العربية</a> | <a href="/en/">English</a></body></html>');
const now=new Date().toISOString().slice(0,10);
W('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${[...new Set(pages)].flatMap(r=>['ar','en'].map(l=>`<url><loc>${U}/${l}/${r}</loc><lastmod>${now}</lastmod><xhtml:link rel="alternate" hreflang="ar" href="${U}/ar/${r}"/><xhtml:link rel="alternate" hreflang="en" href="${U}/en/${r}"/></url>`)).join('')}</urlset>`);
W('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${U}/sitemap.xml\n`);
fs.cpSync('assets','dist/assets',{recursive:true});fs.cpSync('admin','dist/admin',{recursive:true});
W('style.css',`:root{--ink:#12281a;--g:#2c7a2b;--deep:#1b4d1a;--leaf:#6cb33f;--sky:#eef7fc;--sky2:#bfe2f5;--line:#dbe8d6;--red:#c62828}*{box-sizing:border-box;margin:0}html{scroll-behavior:smooth}body{font-family:'IBM Plex Sans Arabic',system-ui,sans-serif;color:var(--ink);line-height:1.85;background:#fff}a{color:inherit;text-decoration:none}:focus-visible{outline:3px solid var(--g);outline-offset:2px}
header{position:sticky;top:0;z-index:5;background:rgba(255,255,255,.96);backdrop-filter:blur(8px);border-bottom:1px solid var(--line)}.bar{max-width:1120px;margin:auto;padding:.5rem 1.2rem;display:flex;align-items:center;gap:1rem;flex-wrap:wrap}.brand{display:flex;gap:.7rem;align-items:center;flex:1;min-width:200px}.brand span{display:flex;flex-direction:column;line-height:1.3}.brand b{font-size:1.2rem;color:var(--deep)}.brand small{font-weight:300;font-size:.78rem}
nav{display:flex;gap:.2rem;flex-wrap:wrap}nav a{padding:.4rem .9rem;border-radius:99px;font-size:.95rem;font-weight:600}nav a:hover{background:var(--sky)}nav a.on{background:var(--g);color:#fff}.sw{border:1.5px solid var(--g);color:var(--deep);padding:.2rem .9rem;border-radius:99px;font-weight:600;font-size:.9rem}
main{max-width:1120px;margin:auto;padding:1.5rem 1.2rem 3rem}h1{font-size:clamp(1.8rem,4vw,2.8rem);line-height:1.3;color:var(--deep);margin-bottom:.8rem}h2{font-size:1.6rem;color:var(--deep);margin:2rem 0 1rem}h3{font-size:1.1rem;color:var(--deep)}.lead{font-size:1.1rem;max-width:42em}.sub{font-weight:300;font-size:1.3rem;margin-bottom:.5rem}.muted{opacity:.6}
.hero{display:grid;grid-template-columns:1.2fr 1fr;gap:2rem;align-items:center;padding:3rem 0;min-height:60vh}.logo{display:grid;place-items:center;aspect-ratio:1;max-width:380px;justify-self:center;width:100%;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff,var(--sky) 55%,var(--sky2))}.logo img{width:80%;height:auto}
.btn{display:inline-block;background:var(--g);color:#fff;padding:.7rem 1.6rem;border-radius:99px;font-weight:600;margin-block:.3rem}.btn:hover{background:var(--deep)}.btn.alt{background:#fff;color:var(--deep);border:1.5px solid var(--g)}
.blk{border-top:1px solid var(--line);padding-block:.5rem}.why{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}.why div{background:var(--sky);padding:1.2rem;border-radius:.5rem 1.2rem 1.2rem .5rem;border-inline-start:5px solid var(--leaf)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:1.2rem;margin-bottom:1rem}.card{display:block;border:1px solid var(--line);border-radius:1rem;overflow:hidden;background:#fff;transition:.2s}a.card:hover{box-shadow:0 8px 24px rgba(27,77,26,.12);transform:translateY(-2px)}.card .im,.prod .im{aspect-ratio:4/3;background:var(--sky);display:grid;place-items:center;overflow:hidden;border-radius:1rem}.card .im{border-radius:0}.im img{width:100%;height:100%;object-fit:cover}.im img.ph{width:38%;height:auto;opacity:.45}.tx{padding:1rem}.tag{display:inline-block;font-size:.78rem;background:var(--sky);color:var(--deep);border-radius:99px;padding:0 .8rem;margin-bottom:.3rem}
.prod{display:grid;grid-template-columns:1fr 1fr;gap:2rem;align-items:start}.crumb{font-size:.9rem;margin-bottom:1rem;opacity:.8}.cta{margin-top:2.5rem;background:var(--deep);color:#fff;text-align:center;border-radius:1.5rem;padding:1.5rem}.cta h2{color:#fff;margin-top:0}.cta .btn{background:#fff;color:var(--deep)}
.contact{background:var(--sky);padding:1.5rem;border-radius:1.5rem;display:grid;gap:.3rem}.contact h2{margin-top:0}.contact a:not(.btn){color:var(--deep);font-weight:600;text-decoration:underline}.soc{display:inline-block;margin-inline-end:.8rem;font-weight:600}.fs a{color:#fff;text-decoration:underline}.icons,.fs{display:flex;gap:.7rem;flex-wrap:wrap}.icons{margin-top:.8rem}.fs{justify-content:center;margin-top:.6rem}.ic{display:block;width:48px;height:48px;border-radius:50%;transition:.2s}.ic:hover{transform:translateY(-2px)}.ic svg,.ic img{width:100%;height:100%;display:block}.fs .ic{width:34px;height:34px}footer{background:var(--deep);color:#fff;text-align:center;padding:1.2rem;font-size:.9rem}
@media(max-width:760px){.hero,.prod{grid-template-columns:1fr}.logo{max-width:240px;order:-1}.hero{padding:1.5rem 0}}`);
console.log('pages',[...new Set(pages)].length*2);
